import { action, internalMutation, internalQuery, mutation } from "./_generated/server";
import { makeFunctionReference } from "convex/server";
import { v } from "convex/values";
import { Doc, Id } from "./_generated/dataModel";

// ─── Shared types ─────────────────────────────────────────────────────────────

type AllTables = {
  packages: Doc<"packages">[];
  blog: Doc<"blog">[];
  services: Doc<"services">[];
  pages: Doc<"pages">[];
  bookings: Doc<"bookings">[];
  contact: Doc<"contact">[];
  companyInfo: Doc<"companyInfo">[];
  heroCarousel: Doc<"heroCarousel">[];
  aboutHero: Doc<"aboutHero">[];
  whoWeAre: Doc<"whoWeAre">[];
  whatWeOffer: Doc<"whatWeOffer">[];
  ourStrength: Doc<"ourStrength">[];
  whyChooseUs: Doc<"whyChooseUs">[];
  testimonials: Doc<"testimonials">[];
  singletons: Doc<"singletons">[];
  socials: Doc<"socials">[];
  media: Doc<"media">[];
};

// Strips _id and _creationTime from a document so Convex generates fresh ones
// on insert. Destructured as parameters so TypeScript's noUnusedParameters rule
// ignores the intentionally discarded _-prefixed bindings.
function stripSystem<T extends { _id: unknown; _creationTime: unknown }>(
  { _id, _creationTime, ...rest }: T
): Omit<T, "_id" | "_creationTime"> {
  void _id;
  void _creationTime;
  return rest as Omit<T, "_id" | "_creationTime">;
}

// makeFunctionReference avoids a circular dependency on the generated
// internal API object (which is re-generated by `npx convex dev`).
const getAllDataRef = makeFunctionReference<
  "query",
  Record<string, never>,
  AllTables
>("migrations:getAllData");

const importDataRef = makeFunctionReference<
  "mutation",
  { tables: AllTables; storageIdMap: Record<string, string> },
  { success: boolean }
>("migrations:importData");

// ─── EXPORT ───────────────────────────────────────────────────────────────────

export const getAllData = internalQuery({
  handler: async (ctx): Promise<AllTables> => {
    const [
      packages,
      blog,
      services,
      pages,
      bookings,
      contact,
      companyInfo,
      heroCarousel,
      aboutHero,
      whoWeAre,
      whatWeOffer,
      ourStrength,
      whyChooseUs,
      testimonials,
      singletons,
      socials,
      media,
    ] = await Promise.all([
      ctx.db.query("packages").collect(),
      ctx.db.query("blog").collect(),
      ctx.db.query("services").collect(),
      ctx.db.query("pages").collect(),
      ctx.db.query("bookings").collect(),
      ctx.db.query("contact").collect(),
      ctx.db.query("companyInfo").collect(),
      ctx.db.query("heroCarousel").collect(),
      ctx.db.query("aboutHero").collect(),
      ctx.db.query("whoWeAre").collect(),
      ctx.db.query("whatWeOffer").collect(),
      ctx.db.query("ourStrength").collect(),
      ctx.db.query("whyChooseUs").collect(),
      ctx.db.query("testimonials").collect(),
      ctx.db.query("singletons").collect(),
      ctx.db.query("socials").collect(),
      ctx.db.query("media").collect(),
    ]);

    return {
      packages,
      blog,
      services,
      pages,
      bookings,
      contact,
      companyInfo,
      heroCarousel,
      aboutHero,
      whoWeAre,
      whatWeOffer,
      ourStrength,
      whyChooseUs,
      testimonials,
      singletons,
      socials,
      media,
    };
  },
});

/**
 * Export all data from the current Convex deployment.
 * Returns all table documents plus resolved download URLs for every stored file.
 * Intended to be called from the migration admin page and downloaded as JSON.
 */
export const exportAll = action({
  handler: async (ctx): Promise<{
    version: string;
    exportedAt: number;
    tables: AllTables;
    storageUrls: Record<string, string>;
  }> => {
    const tables = await ctx.runQuery(getAllDataRef);

    // Collect every unique storage ID referenced across all tables
    const storageIdSet = new Set<Id<"_storage">>();

    for (const doc of tables.packages) storageIdSet.add(doc.imageId);
    for (const doc of tables.blog) storageIdSet.add(doc.imageId);
    for (const doc of tables.heroCarousel) storageIdSet.add(doc.imageId);
    for (const doc of tables.aboutHero) storageIdSet.add(doc.imageId);
    for (const doc of tables.pages) {
      if (doc.heroImageId) storageIdSet.add(doc.heroImageId);
    }
    for (const doc of tables.testimonials) {
      if (doc.avatarImageId) storageIdSet.add(doc.avatarImageId);
    }
    for (const doc of tables.media) storageIdSet.add(doc.storageId);

    // Resolve each storage ID to a permanent download URL
    const storageUrls: Record<string, string> = {};
    for (const storageId of storageIdSet) {
      const url = await ctx.storage.getUrl(storageId);
      if (url) storageUrls[storageId] = url;
    }

    return { version: "1.0", exportedAt: Date.now(), tables, storageUrls };
  },
});

// ─── IMPORT ───────────────────────────────────────────────────────────────────

/**
 * Internal mutation: inserts all exported documents into this deployment's DB,
 * swapping old storage IDs for the new ones produced during re-upload.
 * _id and _creationTime are stripped so Convex generates fresh identifiers.
 */
export const importData = internalMutation({
  args: {
    tables: v.any(),
    storageIdMap: v.record(v.string(), v.string()),
  },
  handler: async (ctx, { tables: rawTables, storageIdMap }) => {
    const tables = rawTables as AllTables;

    const resolveId = (oldId: Id<"_storage"> | undefined): Id<"_storage"> | undefined => {
      if (!oldId) return undefined;
      const newId = storageIdMap[oldId];
      return newId ? (newId as Id<"_storage">) : undefined;
    };

    const resolveUrl = async (id: Id<"_storage"> | undefined): Promise<string | undefined> => {
      if (!id) return undefined;
      return (await ctx.storage.getUrl(id)) ?? undefined;
    };

    // Tables with a required imageId + image URL
    for (const doc of tables.packages) {
      const { imageId, image, ...rest } = stripSystem(doc);
      const newImageId = resolveId(imageId) ?? imageId;
      const newImage = (await resolveUrl(resolveId(imageId))) ?? image;
      await ctx.db.insert("packages", { ...rest, imageId: newImageId, image: newImage });
    }

    for (const doc of tables.blog) {
      const { imageId, image, ...rest } = stripSystem(doc);
      const newImageId = resolveId(imageId) ?? imageId;
      const newImage = (await resolveUrl(resolveId(imageId))) ?? image;
      await ctx.db.insert("blog", { ...rest, imageId: newImageId, image: newImage });
    }

    for (const doc of tables.heroCarousel) {
      const { imageId, image, ...rest } = stripSystem(doc);
      const newImageId = resolveId(imageId) ?? imageId;
      const newImage = (await resolveUrl(resolveId(imageId))) ?? image;
      await ctx.db.insert("heroCarousel", { ...rest, imageId: newImageId, image: newImage });
    }

    for (const doc of tables.aboutHero) {
      const { imageId, image, ...rest } = stripSystem(doc);
      const newImageId = resolveId(imageId) ?? imageId;
      const newImage = (await resolveUrl(resolveId(imageId))) ?? image;
      await ctx.db.insert("aboutHero", { ...rest, imageId: newImageId, image: newImage });
    }

    // pages — optional heroImageId, no URL field
    for (const doc of tables.pages) {
      const { heroImageId, ...rest } = stripSystem(doc);
      await ctx.db.insert("pages", { ...rest, heroImageId: resolveId(heroImageId) });
    }

    // testimonials — optional avatarImageId, no URL field
    for (const doc of tables.testimonials) {
      const { avatarImageId, ...rest } = stripSystem(doc);
      await ctx.db.insert("testimonials", { ...rest, avatarImageId: resolveId(avatarImageId) });
    }

    // media — storageId is its primary reference; skip if image upload failed
    for (const doc of tables.media) {
      const { storageId, ...rest } = stripSystem(doc);
      const newStorageId = resolveId(storageId);
      if (newStorageId) {
        await ctx.db.insert("media", { ...rest, storageId: newStorageId });
      }
    }

    // Tables with no storage references
    for (const doc of tables.services) await ctx.db.insert("services", stripSystem(doc));
    for (const doc of tables.bookings) await ctx.db.insert("bookings", stripSystem(doc));
    for (const doc of tables.contact) await ctx.db.insert("contact", stripSystem(doc));
    for (const doc of tables.companyInfo) await ctx.db.insert("companyInfo", stripSystem(doc));
    for (const doc of tables.whoWeAre) await ctx.db.insert("whoWeAre", stripSystem(doc));
    for (const doc of tables.whatWeOffer) await ctx.db.insert("whatWeOffer", stripSystem(doc));
    for (const doc of tables.ourStrength) await ctx.db.insert("ourStrength", stripSystem(doc));
    for (const doc of tables.whyChooseUs) await ctx.db.insert("whyChooseUs", stripSystem(doc));
    for (const doc of tables.singletons) await ctx.db.insert("singletons", stripSystem(doc));
    for (const doc of tables.socials) await ctx.db.insert("socials", stripSystem(doc));

    return { success: true };
  },
});

/**
 * Import action: called on the TARGET deployment.
 * 1. Re-uploads every image from the source storage URLs into this deployment.
 * 2. Builds an oldId → newId map.
 * 3. Delegates document insertion to importData.
 */
export const importAll = action({
  args: { exportData: v.any() },
  handler: async (ctx, { exportData }) => {
    const { tables, storageUrls } = exportData as {
      tables: AllTables;
      storageUrls: Record<string, string>;
    };

    const storageIdMap: Record<string, string> = {};
    let succeeded = 0;
    let failed = 0;

    for (const [oldId, url] of Object.entries(storageUrls)) {
      try {
        const response = await fetch(url);
        if (!response.ok) {
          console.error(`Failed to fetch image ${oldId}: HTTP ${response.status}`);
          failed++;
          continue;
        }

        const contentType =
          response.headers.get("content-type") ?? "application/octet-stream";
        const blob = new Blob([await response.arrayBuffer()], { type: contentType });

        const uploadUrl = await ctx.storage.generateUploadUrl();
        const uploadRes = await fetch(uploadUrl, {
          method: "POST",
          headers: { "Content-Type": contentType },
          body: blob,
        });

        if (!uploadRes.ok) {
          console.error(`Failed to upload image ${oldId}: HTTP ${uploadRes.status}`);
          failed++;
          continue;
        }

        const { storageId: newId } = (await uploadRes.json()) as { storageId?: string };
        if (newId) {
          storageIdMap[oldId] = newId;
          succeeded++;
        }
      } catch (err) {
        console.error(`Error migrating image ${oldId}:`, err);
        failed++;
      }
    }

    await ctx.runMutation(importDataRef, { tables, storageIdMap });

    return {
      success: true,
      images: { total: Object.keys(storageUrls).length, succeeded, failed },
    };
  },
});

// ─── FIX IMAGE URLs ───────────────────────────────────────────────────────────

/**
 * One-time mutation: after `npx convex import`, the imageId fields are updated
 * to new storage IDs but the plain `image` string fields still contain old
 * deployment URLs. This mutation refreshes every image URL from the current
 * storage so Next.js <Image> stops returning 400 errors.
 *
 * Run once via: npx convex run migrations:fixImageUrls
 */
export const fixImageUrls = mutation({
  handler: async (ctx) => {
    let fixed = 0;

    // packages
    for (const doc of await ctx.db.query("packages").collect()) {
      const url = await ctx.storage.getUrl(doc.imageId);
      if (url && url !== doc.image) {
        await ctx.db.patch(doc._id, { image: url });
        fixed++;
      }
    }

    // blog
    for (const doc of await ctx.db.query("blog").collect()) {
      const url = await ctx.storage.getUrl(doc.imageId);
      if (url && url !== doc.image) {
        await ctx.db.patch(doc._id, { image: url });
        fixed++;
      }
    }

    // heroCarousel
    for (const doc of await ctx.db.query("heroCarousel").collect()) {
      const url = await ctx.storage.getUrl(doc.imageId);
      if (url && url !== doc.image) {
        await ctx.db.patch(doc._id, { image: url });
        fixed++;
      }
    }

    // aboutHero
    for (const doc of await ctx.db.query("aboutHero").collect()) {
      const url = await ctx.storage.getUrl(doc.imageId);
      if (url && url !== doc.image) {
        await ctx.db.patch(doc._id, { image: url });
        fixed++;
      }
    }

    return { fixed };
  },
});
